#!/bin/bash
# Builds biber as a standalone wasm module: a perl interpreter with every XS
# dependency statically linked, plus biber's pure-perl tree in the prefix.
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd)
BUILD=${BUILD:?set BUILD}
SRCDIR=$BUILD/src
DEPS_PREFIX=$BUILD/deps
PERL_SRC=$SRCDIR/perl
HOST_PERL_BUILD=$BUILD/hostperl
PERL_VERSION=${PERL_VERSION:-5.38.2}
PERL_WASM_PREFIX=${PERL_WASM_PREFIX:-$BUILD/prefix}
export AR=${AR:-llvm-ar}

mkdir -p "$BUILD" "$DEPS_PREFIX"

config_var() {
    sed -n "s/^$1='\(.*\)'$/\1/p" "$PERL_SRC/config.sh"
}

apply_patches() {
    cd "$PERL_SRC"
    [ -f .patched ] && return 0
    for p in "$ROOT"/patches/*.patch; do
        patch -p1 -N --no-backup-if-mismatch < "$p"
    done
    touch .patched
}

build_host_perl() {
    [ -x "$HOST_PERL_BUILD/miniperl" ] && return 0
    mkdir -p "$HOST_PERL_BUILD"
    cd "$HOST_PERL_BUILD"
    sh "$PERL_SRC/Configure" -des -Dusedevel -Dmksymlinks -Doptimize=-O0
    make miniperl generate_uudmap
}

build_wasm_perl() {
    cd "$PERL_SRC"
    export EMCC_REAL=$(command -v emcc)
    mkdir -p "$BUILD/shim"
    cp "$ROOT/emcc_configure_shim.sh" "$BUILD/shim/emcc"
    chmod +x "$BUILD/shim/emcc"
    export PATH=$BUILD/shim:$PATH

    export EMPERL_HOSTPERLDIR=$HOST_PERL_BUILD
    export EMPERL_PREFIX=$PERL_WASM_PREFIX
    export EMPERL_STATIC_EXT="Storable Sys/Hostname Unicode/Collate"

    sh Configure -des -Dhintfile=emscripten
    sh "$ROOT/config_fixups.sh" config.sh
    ./Configure -S

    make perl
    install_perl_headers
}

install_perl_headers() {
    site=$(config_var privlib)
    arch=$(config_var archlib)
    rm -rf "$site"
    mkdir -p "$arch/CORE"
    cp -r lib/. "$site/"
    cp ./*.h "$arch/CORE/"
    cp libperl.a "$arch/CORE/"
    chmod -R u+w "$site"
}

merge_archive() {
    target=$1; library=$2; prefix=$3
    staging=$(mktemp -d)
    (cd "$staging" && $AR x "$library")
    for o in "$staging"/*.o; do
        mv "$o" "$(dirname "$o")/$prefix$(basename "$o")"
    done
    $AR r "$target" "$staging"/*.o
    rm -rf "$staging"
}

build_xs_modules() {
    export PERL_WASM_CORE=$(config_var archlib)/CORE
    export PERL_WASM_LIB=$PERL_SRC/lib
    export HOST_PERL="$HOST_PERL_BUILD/miniperl -I$PERL_SRC/lib"
    export HOST_TYPEMAP=$PERL_SRC/lib/ExtUtils/typemap

    # Collides with the identically named symbol in perl's own PerlIO layer.
    sed -i 's/\bPerlIOBase_flush_linebuf\b/utf8strict_flush_linebuf/g' \
        "$SRCDIR/PerlIO-utf8_strict/utf8_strict.xs"
    rm -f "$SRCDIR/PerlIO-utf8_strict/utf8_strict.c"

    # LMUconfig.h is generated by a Makefile.PL that is never otherwise run.
    ( cd "$SRCDIR/List-MoreUtils-XS" && [ -f LMUconfig.h ] || perl Makefile.PL >/dev/null )

    SOMBOK_SRC=$SRCDIR/Unicode-LineBreak/sombok
    [ -d "$SOMBOK_SRC/lib" ] || SOMBOK_SRC=$SRCDIR/sombok
    SOMBOK_SRC=$SOMBOK_SRC DEPS_PREFIX=$DEPS_PREFIX SRCDIR=$SRCDIR bash "$ROOT/build_deps.sh" sombok
    SRCDIR=$SRCDIR DEPS_PREFIX=$DEPS_PREFIX bash "$ROOT/build_deps.sh" libxml2

    grep -vE '^\s*(#|$)' "$ROOT/modules.txt" | while read -r mod ver extra; do
        dir=$SRCDIR/$(echo "$mod" | sed 's/::/-/g')
        case "${extra:-}" in
            btparse)
                SRCDIR=$SRCDIR DEPS_PREFIX=$DEPS_PREFIX bash "$ROOT/build_deps.sh" btparse "$dir"
                MODVER=$ver bash "$ROOT/build_xs.sh" "$dir" "$mod" "-I$dir/btparse/src"
                $AR r "$PERL_WASM_LIB/auto/Text/BibTeX/BibTeX.a" "$dir"/btparse/src/*.o
                ;;
            sombok)
                MODVER=$ver bash "$ROOT/build_xs.sh" "$dir" "$mod" "-I$DEPS_PREFIX/sombok/include"
                merge_archive "$PERL_WASM_LIB/auto/Unicode/LineBreak/LineBreak.a" \
                              "$DEPS_PREFIX/sombok/lib/libsombok.a" sombok_
                ;;
            libxml2)
                MODVER=$ver bash "$ROOT/build_xs.sh" "$dir" "$mod" "-I$DEPS_PREFIX/libxml2/include/libxml2"
                merge_archive "$PERL_WASM_LIB/auto/XML/LibXML/LibXML.a" \
                              "$DEPS_PREFIX/libxml2/lib/libxml2.a" xml2_
                ;;
            *)
                MODVER=$ver bash "$ROOT/build_xs.sh" "$dir" "$mod" "${extra:-}"
                ;;
        esac
    done
}

dedupe_static_ext() {
    objcopy=$(dirname "$(command -v emcc)")/../bin/llvm-objcopy
    [ -x "$objcopy" ] || objcopy=$(command -v llvm-objcopy || true)
    [ -x "$objcopy" ] || return 0
    nm_tool=$(dirname "$objcopy")/llvm-nm
    [ -x "$nm_tool" ] || return 0

    core=$(mktemp)
    "$nm_tool" --defined-only --extern-only libperl.a 2>/dev/null | awk '{print $NF}' | sort -u > "$core"

    for a in $(sed -n "s/^static_ext='\(.*\)'$/\1/p" config.sh); do
        archive=lib/auto/$a/${a##*/}.a
        [ -f "$archive" ] || continue
        dups=$("$nm_tool" --defined-only --extern-only "$archive" 2>/dev/null | awk '{print $NF}' | sort -u | comm -12 - "$core")
        [ -n "$dups" ] || continue
        args=""
        for d in $dups; do
            args="$args --redefine-sym $d=perlext_$d"
        done
        echo "renaming duplicate symbols in $archive"
        "$objcopy" $args "$archive"
    done
    rm -f "$core"
}

link_biber() {
    cd "$PERL_SRC"
    exts=$(grep -vE '^\s*(#|$)' "$ROOT/modules.txt" | awk '{gsub(/::/,"/",$1); printf "%s ", $1}')
    perl -i -pe "s{^static_ext='(.*)'\$}{static_ext='\$1 $exts'}" config.sh

    # An extension that moved to pure perl in a newer release produces no
    # archive, and the link fails on the missing file rather than skipping it.
    kept=""
    for e in $(sed -n "s/^static_ext='\(.*\)'$/\1/p" config.sh); do
        if [ -f "lib/auto/$e/${e##*/}.a" ]; then
            kept="$kept $e"
        else
            echo "skipping static ext $e: no archive built"
        fi
    done
    perl -i -pe "s{^static_ext='.*'\$}{static_ext='$kept'}" config.sh

    ./Configure -S
    rm -f perlmain.c perlmain.o nodeperl_dev.js
    dedupe_static_ext
    make perl
    install_perl_headers
}

install_biber_tree() {
    site=$(config_var sitelib)
    [ -f /usr/share/perl5/Biber.pm ] || { echo "biber package not installed on the host"; exit 1; }
    rm -rf "$site"
    mkdir -p "$site"
    cp -r /usr/share/perl5/. "$site/"
    chmod -R u+w "$site"

    # From the same sources the XS was built from, so the perl side and the
    # linked bootstrap agree on version.
    grep -vE '^\s*(#|$)' "$ROOT/modules.txt" | while read -r mod ver extra; do
        dir=$SRCDIR/$(echo "$mod" | sed 's/::/-/g')
        [ -d "$dir/lib" ] && cp -r "$dir/lib/." "$site/"
        leaf=${mod##*::}
        if [ -f "$dir/$leaf.pm" ]; then
            sub=$(echo "${mod%::*}" | sed 's|::|/|g')
            [ "$sub" = "$mod" ] && sub=.
            mkdir -p "$site/$sub"
            cp "$dir/$leaf.pm" "$site/$sub/"
        fi
    done

    cp -r "$SRCDIR/biber/lib/." "$site/"
    chmod -R u+w "$site"
    install -D -m 755 "$SRCDIR/biber/bin/biber" "$PERL_WASM_PREFIX/bin/biber"
}

SRCDIR=$SRCDIR PERL_VERSION=$PERL_VERSION BIBER_VERSION=${BIBER_VERSION:-2.19} bash "$ROOT/fetch_sources.sh"
apply_patches
build_host_perl
build_wasm_perl
build_xs_modules
link_biber
install_biber_tree

cp "$PERL_SRC/nodeperl_dev.js" "$BUILD/biber.js"
[ -f "$PERL_SRC/nodeperl_dev.wasm" ] && cp "$PERL_SRC/nodeperl_dev.wasm" "$BUILD/biber.wasm"
[ "$PERL_WASM_PREFIX" = "$BUILD/prefix" ] || cp -r "$PERL_WASM_PREFIX" "$BUILD/prefix"
echo "biber wasm module in $BUILD"
